**Question Set 8**

**Implement Reinforcement Learning (Q-Learning) for Energy Consumption Optimization**

#### Step 1: Define States and Actions

In [8]:
import numpy as np
import random

states = ["Low", "Medium", "High"]   #load conditions
actions = ["Reduce", "Maintain", "Increase"]    #power 

#### Step 2: Initialize Q-Table

In [9]:
Q = np.zeros((len(states), len(actions)))

In [10]:
Q

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Step 3: Define Parameters

In [12]:
alpha = 0.1  #learning rate
gamma = 0.9   #Discount factor >>> higher value
epsilon = 0.2   # Exploration rate 

#### Step 4: Define Reward Matrix

In [13]:
rewards = np.array([
    [5, 2, -1],
    [3, 4, 0],
    [-2, 2, 5]
])

#### Step 5: Training (Q-Learning)

In [14]:
episodes = 1000

for episode in range(episodes):
    state = random.randint(0,2)

    if random.uniform(0,1) < epsilon:
        action = random.randint(0,2)
    else:
        action = np.argmax(Q[state])

    reward = rewards[state][action]
    next_state = random.randint(0,2)

    Q[state][action] = Q[state][action] + alpha * (
        reward + gamma * np.max(Q[next_state]) - Q[state][action]
    )

print("Q-Table:\n", Q)

Q-Table:
 [[41.44469254 29.84856881 26.43901423]
 [39.69505261 31.8108776  28.02607884]
 [27.15680378 21.7962224  41.76687525]]


#### Step 6: Extract Optimal Policy

In [15]:
print("\nBest Policy:")
for i in range(len(states)):
    print(states[i], "->", actions[np.argmax(Q[i])])


Best Policy:
Low -> Reduce
Medium -> Reduce
High -> Increase


**1. What is Reinforcement Learning?**

It is a machine learning technique where an agent learns by interacting with the environment using rewards and penalties.

**2. What is Q-Learning?**

Q-Learning is a model-free reinforcement learning algorithm that learns the best action for each state using a Q-table.

**3. What is a Q-Table?**

It is a table that stores values representing the quality (Q-value) of taking a particular action in a given state.

**4. What are states and actions in this experiment?**

States represent machine load levels or robot positions, and actions represent possible decisions like reduce power or move direction.

**5. What is the role of reward in RL?**

Reward guides the agent to take better actions by giving positive or negative feedback.